// Datos semilla iniciales para UNIVERCE CELU
const initialProducts = [
  // 1. Cargadores
  {
    id: "cabezal-apple-20w",
    name: "Cabezal Apple 20W USB-C",
    category: "cargadores",
    price: 18500,
    originalPrice: 22000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673394/pyfo8bnllfp0x9aauyun.jpg",
    description: "Adaptador de corriente USB-C original de 20W para Apple iPhone y iPad. Ofrece una carga rápida y eficiente en cualquier lugar.",
    badge: "Más Vendido",
    available: true,
    featured: true
  },
  {
    id: "cabezal-samsung-25w",
    name: "Cabezal Samsung 25W Super Fast Charging",
    category: "cargadores",
    price: 16900,
    originalPrice: 19500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673395/e5dsco3oo1ppzlgpw2bc.jpg",
    description: "Cargador rápido original Samsung 25W con puerto USB tipo C. Compatible con protocolo de carga Super Fast Charging para celulares Galaxy compatibles.",
    badge: "Super Fast",
    available: true,
    featured: true
  },
  {
    id: "auriculares-cable-samsung-ehs61",
    name: "Auriculares con Cable Samsung EHS61 3.5mm",
    category: "audio",
    price: 4900,
    originalPrice: 6500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673396/vqx8t739vfho8yygj1gi.jpg",
    description: "Auriculares manos libres clásicos con conector Jack de 3.5mm. Incluyen control de volumen y micrófono integrado con sonido estéreo nítido.",
    badge: "Clásico",
    available: true,
    featured: false
  },
  {
    id: "galaxy-buds2-pro",
    name: "Auriculares Inalámbricos Galaxy Buds2 Pro",
    category: "audio",
    price: 89000,
    originalPrice: 98000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673398/fdmlomkktcig4v5qqejg.jpg",
    description: "Auriculares inalámbricos premium TWS con cancelación activa de ruido (ANC), audio de 24 bits de alta fidelidad y ajuste ergonómico avanzado.",
    badge: "Premium ANC",
    available: true,
    featured: true
  },
  {
    id: "cargador-samsung-25w-completo",
    name: "Cargador Samsung 25W Completo",
    category: "cargadores",
    price: 24500,
    originalPrice: 28900,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673399/lkayfatx9le9h7nechbn.jpg",
    description: "Combo definitivo que incluye cabezal cargador ultra rápido Samsung de 25W y cable reforzado original USB-C a USB-C de 1 metro.",
    badge: "Kit Completo",
    available: true,
    featured: true
  },
  {
    id: "cabezal-samsung-45w",
    name: "Cabezal Samsung 45W Ultra Fast Charging",
    category: "cargadores",
    price: 26000,
    originalPrice: 31000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673402/fsiljh9u7tmm9ymeuyie.jpg",
    description: "Adaptador de pared Samsung de 45W equipado con Super Fast Charging 2.0. Ideal para Galaxy S23/S24 Ultra y tablets de alta gama.",
    badge: "Max Power",
    available: true,
    featured: true
  },
  {
    id: "auriculares-cable-samsung-akg-c",
    name: "Auriculares con Cable Samsung AKG Tipo-C",
    category: "audio",
    price: 11900,
    originalPrice: 14500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673404/s95hemc79bbw2rvea8ad.jpg",
    description: "Auriculares originales afinados por AKG con conexión directa USB Tipo C. Graves profundos y agudos nítidos con micrófono integrado y manos libres.",
    badge: "AKG Sound",
    available: true,
    featured: false
  },
  {
    id: "cargador-samsung-45w-completo",
    name: "Cargador Samsung 45W Completo",
    category: "cargadores",
    price: 33500,
    originalPrice: 39900,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673405/s9wcvkapqjv2hbd2llkd.jpg",
    description: "Kit premium con cabezal de carga Super Fast Charging 2.0 de 45W y cable de alta conductividad USB-C a USB-C de 5A.",
    badge: "Recomendado",
    available: true,
    featured: true
  },
  {
    id: "cable-samsung-c-a-c",
    name: "Cable Samsung USB-C a USB-C (3A, 1m)",
    category: "cables",
    price: 7900,
    originalPrice: 9500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673406/ymgwxols0rsvh1jazayi.jpg",
    description: "Cable de carga rápida original Samsung Tipo C a Tipo C compatible con hasta 60W (3A) de potencia para transferencia y carga fluida.",
    badge: "Original",
    available: true,
    featured: false
  },
  {
    id: "cargador-motorola-68w-duo",
    name: "Cargador Motorola TurboPower 68W Duo",
    category: "cargadores",
    price: 32000,
    originalPrice: 38000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673408/qxnqbwgmcioorpyqwntr.jpg",
    description: "Cargador de pared Motorola con doble puerto USB-C inteligente de 68W. Carga tu laptop y celular Motorola al mismo tiempo con la máxima velocidad.",
    badge: "Duo Turbo",
    available: true,
    featured: true
  },
  {
    id: "cable-motorola-turbo-a-c",
    name: "Cable Motorola Turbo USB-A a USB-C (1m)",
    category: "cables",
    price: 6900,
    originalPrice: 8500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673409/ijoh8caewf02mm5dbihh.jpg",
    description: "Cable original Motorola con puertos USB-A a USB-C reforzado. Ideal para cargadores TurboPower de modelos clásicos.",
    badge: "Reforzado",
    available: true,
    featured: false
  },
  {
    id: "cargador-motorola-125w",
    name: "Cargador Motorola TurboPower 125W",
    category: "cargadores",
    price: 49000,
    originalPrice: 58000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673411/wg3c518mkouyhycnyjhs.jpg",
    description: "El cargador más potente de Motorola. 125W de potencia pura USB-C GaN de tamaño ultra compacto para cargar notebooks y celulares Edge compatibles en minutos.",
    badge: "125W GaN",
    available: true,
    featured: true
  },
  {
    id: "funda-magsafe-transparente",
    name: "Funda Transparente MagSafe Premium",
    category: "fundas",
    price: 11900,
    originalPrice: 15000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673412/kjv4n2i286wshrlz2rly.jpg",
    description: "Funda transparente de acrílico rígido con anillo de imanes MagSafe integrado. No se pone amarilla y protege contra caídas fuertes.",
    badge: "MagSafe",
    available: true,
    featured: true
  },
  {
    id: "funda-magnetica-utryee",
    name: "Funda Magnética Utryee (iPhone 15/16 Pro)",
    category: "fundas",
    price: 13900,
    originalPrice: 18000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673413/xj17zt67wpoveruywujn.jpg",
    description: "Funda premium de alta resistencia marca Utryee con soporte magnético integrado y acabado mate elegante para iPhone 15 y 16 Pro.",
    badge: "Utryee Design",
    available: true,
    featured: true
  },
  {
    id: "vidrio-templado-9d",
    name: "Vidrio Templado 9D Full Glue",
    category: "vidrios",
    price: 3900,
    originalPrice: 5000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673414/bdutha53t67pikouxpkl.jpg",
    description: "Protector de vidrio templado 9D con adhesivo completo (Full Glue) en toda la pantalla. Dureza 9H contra rayaduras y roturas de display.",
    badge: "Anti Impacto",
    available: true,
    featured: true
  },
  {
    id: "tripode-profesional-aro",
    name: "Trípode Extensible Profesional para Aro de Luz",
    category: "otros",
    price: 14900,
    originalPrice: 19000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673416/scok8pssi8oqrmfammpo.jpg",
    description: "Trípode metálico reforzado ajustable hasta 2.1 metros de altura con rosca estándar, perfecto para aros de luz LED, cámaras o smartphones.",
    badge: "Ajustable",
    available: true,
    featured: false
  },
  {
    id: "aro-luz-selfie-rosa",
    name: "Aro de Luz Selfie Clip Ringo Rosa",
    category: "otros",
    price: 4500,
    originalPrice: 6000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673417/p1pk4osq35g5lil5hspu.jpg",
    description: "Aro de luz LED recargable portátil tipo broche/clip para encastrar en el celular. Brinda una iluminación excelente para selfies y videollamadas.",
    badge: "Selfie Star",
    available: true,
    featured: false
  },
  {
    id: "baston-selfie-fetuzz-fsr003",
    name: "Bastón Selfie Trípode Fetuzz F-SR003",
    category: "otros",
    price: 12900,
    originalPrice: 16500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673418/ay8gd0uo7wtdcmqfq2f8.jpg",
    description: "Bastón selfie premium de metal convertible en trípode cuadripie estable, con control remoto Bluetooth desmontable. Marca Fetuzz.",
    badge: "Fetuzz Original",
    available: true,
    featured: true
  },
  {
    id: "aro-luz-rgb-33cm",
    name: "Aro de Luz Led RGB 33cm con Soporte",
    category: "otros",
    price: 18900,
    originalPrice: 24000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673420/pj6rzcv7n8ebaeqivapp.jpg",
    description: "Aro de luz LED multicolor RGB de 33cm de diámetro con múltiples modos de colores, efectos dinámicos, regulador de intensidad y soporte flexible.",
    badge: "RGB Pro",
    available: true,
    featured: true
  },
  {
    id: "aro-luz-33cm-tripode",
    name: "Aro de Luz Led 33cm con Trípode",
    category: "otros",
    price: 22000,
    originalPrice: 28000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673421/dbxs0tggmjdv3nq8qzmo.jpg",
    description: "Kit completo que incluye aro de luz LED de 33cm de 3 tonos de luz blanca y cálida regulable, más trípode extensible de aluminio de 2 metros.",
    badge: "Kit Studio",
    available: true,
    featured: false
  },
  {
    id: "micro-sd-kingston-128gb",
    name: "Tarjeta MicroSD Kingston 128GB Clase 10",
    category: "otros",
    price: 14500,
    originalPrice: 18000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673422/qdifryhqothw8qcqw33b.jpg",
    description: "Tarjeta de memoria MicroSD Kingston Canvas Select Plus de 128GB de velocidad ultra rápida optimizada para dispositivos móviles Android.",
    badge: "A1 Speed",
    available: true,
    featured: true
  },
  {
    id: "micro-sd-kingston-64gb",
    name: "Tarjeta MicroSD Kingston 64GB Clase 10",
    category: "otros",
    price: 9900,
    originalPrice: 12500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673423/ccavwvad4dvwivpy4sni.jpg",
    description: "Tarjeta de memoria de 64GB Kingston Canvas Select Plus con adaptador SD. Ideal para almacenar fotos, videos Full HD y música.",
    badge: "Kingston",
    available: true,
    featured: false
  },
  {
    id: "pendrive-kingston-exodia-64gb",
    name: "Pendrive Kingston DataTraveler Exodia 64GB USB 3.2",
    category: "otros",
    price: 8900,
    originalPrice: 11000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673425/rsdutseps1i84jjcxz7s.jpg",
    description: "Pendrive USB 3.2 Gen 1 de alta velocidad con capuchón protector de colores y práctico enganche para llavero. Ideal para oficinas y estudiantes.",
    badge: "USB 3.2",
    available: true,
    featured: false
  },
  {
    id: "auriculares-tws-a6s",
    name: "Auriculares Inalámbricos TWS A6S MiPods",
    category: "audio",
    price: 7900,
    originalPrice: 11000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673426/nnjahrfhlqu1mnl2tcxx.jpg",
    description: "Auriculares inalámbricos Bluetooth súper económicos A6S con estuche cargador magnético inteligente y botón físico multifunción.",
    badge: "Super Económico",
    available: true,
    featured: true
  },
  {
    id: "joystick-ps4-dualshock-4",
    name: "Joystick PlayStation DualShock 4",
    category: "otros",
    price: 38000,
    originalPrice: 45000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673427/mtsugrhcx8hh8oksdq3u.jpg",
    description: "Controlador inalámbrico bluetooth para PS4 y PC con panel táctil capacitivo, barra luminosa, conector jack de audio integrado y vibración premium.",
    badge: "Gaming",
    available: true,
    featured: true
  },
  {
    id: "combo-teclado-mouse-gtc",
    name: "Combo Teclado y Mouse Inalámbrico GTC Soft Duo",
    category: "otros",
    price: 24900,
    originalPrice: 31000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673429/o1ougen9fzelmmrt1tmz.jpg",
    description: "Kit de oficina inalámbrico GTC silencioso y ergonómico. Conexión USB dongle única para ambos periféricos y ahorro inteligente de energía.",
    badge: "GTC Office",
    available: true,
    featured: false
  },
  {
    id: "adaptador-hub-5en1-gtc",
    name: "Adaptador Hub Multi-puerto USB-C GTC 5 en 1",
    category: "cables",
    price: 18900,
    originalPrice: 24000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673430/djmudob9yrqaislfsrae.jpg",
    description: "Adaptador HUB USB-C metálico premium que expande un puerto tipo C en salida HDMI 4K, 3 puertos USB 3.0 de alta velocidad y puerto de carga PD.",
    badge: "HUB Pro",
    available: true,
    featured: true
  },
  {
    id: "adaptador-hub-4en1-lambo",
    name: "Adaptador Hub Multi-puerto USB Lambo Tech 4 en 1",
    category: "cables",
    price: 11500,
    originalPrice: 14900,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673431/orhlsqffbcd1elj0zh0p.jpg",
    description: "Hub de expansión USB 3.0 de 4 puertos metálico marca Lambo Tech. Ideal para conectar múltiples accesorios a tu computadora de forma segura.",
    badge: "Lambo Tech",
    available: true,
    featured: false
  },
  {
    id: "cargador-rapido-puxida-2a",
    name: "Cargador Rápido Puxida 2.1A con Cable USB-C",
    category: "cargadores",
    price: 8900,
    originalPrice: 12000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673433/kgaw1xxnwzrzazwovveh.jpg",
    description: "Cargador de pared económico marca Puxida con corriente de salida estable de 2.1A y cable de carga rápida USB Tipo C incluido en caja.",
    badge: "Eco Rápido",
    available: true,
    featured: false
  },
  {
    id: "repetidor-wifi-300mbps",
    name: "Repetidor Extensor de Señal Wifi 300Mbps",
    category: "otros",
    price: 15900,
    originalPrice: 21000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673434/c2npebwgtfpwjgurtn0k.jpg",
    description: "Extensor de alcance de señal Wifi inalámbrico a 300Mbps. Cuenta con dos antenas internas potentes, configuración rápida por WPS y puerto Ethernet.",
    badge: "Wifi Boost",
    available: true,
    featured: true
  },
  {
    id: "microfono-corbatero-doble-ringo",
    name: "Micrófono Corbatero Inalámbrico Doble Ringo USB-C",
    category: "audio",
    price: 28900,
    originalPrice: 36000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673438/gi225bmre6nyytn9gcha.jpg",
    description: "Sistema de micrófono lavalier corbatero inalámbrico doble (2 micrófonos y 1 receptor USB-C) marca Ringo, ideal para videos de TikTok y streaming.",
    badge: "Ringo Sound",
    available: true,
    featured: true
  },
  {
    id: "funda-sumergible-impermeable",
    name: "Funda Sumergible Impermeable Universal",
    category: "fundas",
    price: 3500,
    originalPrice: 4800,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673440/aj4z68nwzpc7xhkpsoxx.jpg",
    description: "Bolsa protectora estanca sumergible universal con doble cierre hermético y ventana transparente táctil. Excelente para piletas y vacaciones.",
    badge: "Waterproof",
    available: true,
    featured: false
  },
  {
    id: "mousepad-ergonomico-gtc",
    name: "Mousepad Ergonómico GTC Gel PAD-212",
    category: "otros",
    price: 6900,
    originalPrice: 8500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673441/xarvhiasequxqo8syqk5.jpg",
    description: "Pad para mouse ergonómico marca GTC con apoyamuñecas relleno de gel suave de memoria que previene el síndrome del túnel carpiano.",
    badge: "Gel Confort",
    available: true,
    featured: false
  },
  {
    id: "mouse-inalambrico-silencioso-gtc",
    name: "Mouse Inalámbrico Silencioso GTC Office",
    category: "otros",
    price: 8900,
    originalPrice: 11500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673443/odhwr7ggj2qe4uggmmak.jpg",
    description: "Mouse inalámbrico ultra delgado marca GTC con clics silenciosos. Resolución de 1600 DPI regulables y sensor óptico de precisión.",
    badge: "Silent Click",
    available: true,
    featured: false
  },
  {
    id: "adaptador-hdmi-a-vga-audio",
    name: "Adaptador Conversor HDMI a VGA con Audio 1080p",
    category: "cables",
    price: 7900,
    originalPrice: 10000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673444/edixe51q6grte9yjyely.jpg",
    description: "Cable adaptador conversor digital a analógico de entrada HDMI a salida VGA 1080p. Incluye cable jack de audio auxiliar para sonido independiente.",
    badge: "Conversor",
    available: true,
    featured: false
  },
  {
    id: "soporte-cargador-3en1-magsafe",
    name: "Soporte Cargador Inalámbrico 3 en 1 MagSafe",
    category: "cargadores",
    price: 34900,
    originalPrice: 42000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673445/kfynicpsyz5dkirhu8ko.jpg",
    description: "Estación de carga rápida inalámbrica MagSafe 3 en 1. Carga en simultáneo tu iPhone compatible, Apple Watch y AirPods de forma elegante.",
    badge: "Premium 3-in-1",
    available: true,
    featured: true
  },
  {
    id: "powerbank-kaber-10000mah",
    name: "Cargador Portátil Power Bank Kaber 10000mAh",
    category: "cargadores",
    price: 19900,
    originalPrice: 26000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673446/jvvinbdaj4brxpqwobpb.jpg",
    description: "Cargador portátil de batería Power Bank de 10000mAh marca Kaber. Equipada con puertos USB duales de carga rápida y display digital de porcentaje.",
    badge: "10000mAh",
    available: true,
    featured: true
  },
  {
    id: "cable-c-a-a-protection-mobile",
    name: "Cable Tipo-C a USB-A Protection Mobile 1.2m",
    category: "cables",
    price: 4900,
    originalPrice: 6500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673448/zkyoath9mabs7lolr3i1.jpg",
    description: "Cable USB a tipo C marca Protection Mobile reforzado con malla de nylon y fichas de metal. Soporta carga súper rápida de 1.2 metros de largo.",
    badge: "Malla Nylon",
    available: true,
    featured: false
  },
  {
    id: "cable-micro-usb-protection-mobile",
    name: "Cable Micro-USB Protection Mobile 1.2m",
    category: "cables",
    price: 4500,
    originalPrice: 5800,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673449/txo55hkhchlchjvhuayv.jpg",
    description: "Cable de carga y transferencia de datos USB-A a conector clásico Micro-USB (V8) marca Protection Mobile con conectores blindados.",
    badge: "Blindado",
    available: true,
    featured: false
  },
  {
    id: "redmi-buds-3-lite",
    name: "Auriculares Xiaomi Redmi Buds 3 Lite",
    category: "audio",
    price: 21900,
    originalPrice: 28000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673451/p7nfbqkgeauzi3wk3m5a.jpg",
    description: "Auriculares inalámbricos Xiaomi Redmi Buds 3 Lite TWS con conectividad Bluetooth 5.2, baja latencia para gaming, resistencia al agua IP54 y 18hs de batería.",
    badge: "Xiaomi Original",
    available: true,
    featured: true
  },
  {
    id: "jbl-flip-6-bluetooth",
    name: "Parlante Portátil Bluetooth JBL Flip 6",
    category: "audio",
    price: 139000,
    originalPrice: 155000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673452/wnrpypfnji8rs7v50ovy.jpg",
    description: "Parlante inalámbrico bluetooth JBL original. Sonido potente de 2 vías con graves súper profundos, resistencia al agua IP67 y hasta 12 horas de reproducción continua.",
    badge: "JBL Premium",
    available: true,
    featured: true
  },
  {
    id: "jbl-go-3-portatil",
    name: "Parlante Portátil Bluetooth JBL Go 3",
    category: "audio",
    price: 49000,
    originalPrice: 58000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673454/hb7mendbev2xqikrmvea.jpg",
    description: "Parlante ultra compacto e impermeable JBL Go 3. Sonido Pro de alta fidelidad, diseño de tela de moda resistente al agua IP67 y enganche integrado.",
    badge: "JBL Go",
    available: true,
    featured: true
  },
  {
    id: "camara-seguridad-foco-boumen",
    name: "Cámara de Seguridad Wifi Foco BM Boumen",
    category: "otros",
    price: 24900,
    originalPrice: 32000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673456/w1baoekaqmwuaqaqiwtd.jpg",
    description: "Cámara de seguridad panorámica 360 grados tipo lámpara (rosca de foco común) marca BM Boumen. Monitoreo por app móvil, visión nocturna infrarroja y audio bidireccional.",
    badge: "Seguridad Hogar",
    available: true,
    featured: true
  },
  {
    id: "android-tv-stick-4k",
    name: "Android TV Stick 4K Ultra HD TVR3",
    category: "otros",
    price: 36000,
    originalPrice: 44000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673458/gylzwwgqbyn6v1vftokj.jpg",
    description: "Convertidor de Smart TV stick compacto en formato pendrive con salida HDMI 4K. Conexión Wifi dual band para descargar Netflix, YouTube y aplicaciones Android.",
    badge: "Android TV",
    available: true,
    featured: true
  },
  {
    id: "auriculares-gamer-noga-stormer",
    name: "Auriculares Gamer Noga Stormer NG-8620",
    category: "audio",
    price: 18900,
    originalPrice: 24000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673460/n0cbiopyz9d6og9vaj2t.jpg",
    description: "Auriculares vincha gamer marca Noga Stormer. Almohadillas ultra acolchadas, luces de colores LED RGB integradas, micrófono flexible ajustable y sonido súper envolvente de juego.",
    badge: "Noga Gamer",
    available: true,
    featured: false
  },
  {
    id: "termo-stanley-burgundy-13l",
    name: "Termo Stanley Classic Burgundy 1.3L",
    category: "otros",
    price: 99000,
    originalPrice: 110000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673464/wj2r6rx8slpenzufpa59.jpg",
    description: "Termo clásico Stanley original color Burgundy (Bordó) de 1.3 litros con tapón cebador de gran caudal. Mantiene la temperatura caliente o fría por más de 24 horas.",
    badge: "Stanley Original",
    available: true,
    featured: true
  },
  {
    id: "termo-stanley-blue-13l",
    name: "Termo Stanley Classic Blue 1.3L",
    category: "otros",
    price: 99000,
    originalPrice: 110000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673466/sfkp6yfikpequx54gki4.jpg",
    description: "Termo original Stanley color azul clásico de acero inoxidable 18/8 de doble pared con aislamiento al vacío de 1.3 litros. Sello a prueba de fugas.",
    badge: "Stanley",
    available: true,
    featured: false
  },
  {
    id: "kit-accesorios-apple-completo",
    name: "Kit de Accesorios Apple Premium",
    category: "cargadores",
    price: 29900,
    originalPrice: 38000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673468/gyofxjij0i0c3pk2pwew.jpg",
    description: "Kit premium para usuarios de Apple. Incluye cargador de pared de 20W USB-C de carga rápida PD, cable USB-C a Lightning, y auriculares in-ear clásicos Earpods.",
    badge: "Apple Combo",
    available: true,
    featured: true
  },
  {
    id: "kit-cargadores-samsung-duo",
    name: "Kit Adaptadores Samsung (45W + 25W)",
    category: "cargadores",
    price: 36900,
    originalPrice: 46000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673470/loiocv16xc4ulq0vvl8k.jpg",
    description: "Kit de carga definitiva en el hogar. Incluye el adaptador de carga rápida súper potente de 45W para el celular principal y el cabezal de 25W para el secundario.",
    badge: "Samsung Combo",
    available: true,
    featured: false
  },
  {
    id: "auriculares-jbl-tune500-760",
    name: "Combo Auriculares JBL Tune500BT + Tune760NC",
    category: "audio",
    price: 119000,
    originalPrice: 138000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673472/p7pga59fkrh4kc1l76ny.jpg",
    description: "Doble experiencia de sonido original JBL. Llévate el JBL Tune500BT supraural súper cómodo e inalámbrico y el potente Tune760NC con cancelación activa de ruido.",
    badge: "JBL Duo Combo",
    available: true,
    featured: true
  },
  {
    id: "fundas-iphone-17-max-surtido",
    name: "Surtido Fundas iPhone 17 Pro Max",
    category: "fundas",
    price: 10900,
    originalPrice: 14000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673474/sxxcgj4eoizsm9zboihg.jpg",
    description: "Nueva gama de fundas protectoras con diseño avanzado antiimpacto y compatibilidad de carga mejorada para la serie iPhone 17 Pro Max.",
    badge: "Nueva Serie",
    available: true,
    featured: true
  },
  {
    id: "joystick-sony-dualsense-ps5",
    name: "Joystick Sony DualSense para PS5",
    category: "otros",
    price: 79000,
    originalPrice: 89000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673478/ozpi6l482oiuafltxml3.jpg",
    description: "Control de juegos original inalámbrico DualSense de Sony PlayStation 5. Gatillos adaptativos, retroalimentación háptica premium y micrófono integrado.",
    badge: "PS5 Gaming",
    available: true,
    featured: true
  },
  {
    id: "airpods-tws-premium-pro",
    name: "Auriculares Inalámbricos AirPods Pro TWS",
    category: "audio",
    price: 24900,
    originalPrice: 32000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673479/bsvaeoqqjulbv0kcdnhw.jpg",
    description: "Auriculares de formato idéntico AirPods Pro réplica premium con estuche inteligente de carga, conexión automática pop-up y control táctil dinámico.",
    badge: "AirPods Style",
    available: true,
    featured: true
  },
  {
    id: "joystick-ps4-dualshock-surtido",
    name: "Joystick PS4 DualShock 4 Surtido de Colores",
    category: "otros",
    price: 36000,
    originalPrice: 42000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673480/a23f6rahevpiqtexip48.jpg",
    description: "Controladores inalámbricos para consolas PlayStation 4 en variedad de colores especiales (Camuflados, Oro, Azul, Rojo) inalámbricos.",
    badge: "Colores Surtidos",
    available: true,
    featured: false
  },
  {
    id: "jbl-tour-pro-2-tws",
    name: "Auriculares Inalámbricos JBL Tour Pro 2",
    category: "audio",
    price: 189000,
    originalPrice: 210000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673482/wevamikdmcjoiulsqk1s.jpg",
    description: "Auriculares TWS inalámbricos premium de gama ultra alta JBL con cancelación de ruido inteligente de alta fidelidad y estuche con pantalla táctil LED inteligente.",
    badge: "Gama Alta",
    available: true,
    featured: true
  },
  {
    id: "jbl-wave-380-tws",
    name: "Auriculares Inalámbricos JBL Wave 380",
    category: "audio",
    price: 69000,
    originalPrice: 79000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673484/gxbw5plq7hpjs1x9anlg.jpg",
    description: "Auriculares de gran ergonomía y sonido JBL Deep Bass Wave 380 con hasta 32 horas de batería total en estuche magnético, excelente calidad.",
    badge: "JBL Deep Bass",
    available: true,
    featured: false
  },
  {
    id: "samsung-buds3-pro",
    name: "Auriculares Inalámbricos Galaxy Buds3 Pro",
    category: "audio",
    price: 199000,
    originalPrice: 220000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673485/bx3wc6te7msqxcjjk5tl.jpg",
    description: "Nueva generación de auriculares inalámbricos Samsung de alta fidelidad con cancelación activa de ruido adaptativa por inteligencia artificial, luces led y sonido 360.",
    badge: "Galaxy AI",
    available: true,
    featured: true
  },
  {
    id: "micro-sd-kingston-32gb",
    name: "Tarjeta MicroSD Kingston 32GB Clase 10",
    category: "otros",
    price: 6900,
    originalPrice: 8500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673486/i5qq1ttmwjgvyo97kzm1.jpg",
    description: "Tarjeta de memoria de 32GB Kingston Canvas Select Plus con velocidad de transferencia Clase 10 y adaptador SD para múltiples dispositivos.",
    badge: "Eco Memory",
    available: true,
    featured: false
  },
  {
    id: "fundas-iphone-16-silicone-pack",
    name: "Fundas iPhone 16 Pro Silicone Cases",
    category: "fundas",
    price: 9900,
    originalPrice: 12500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673488/yukdms3tde3vhh38w8kr.jpg",
    description: "Fundas oficiales de silicona suave al tacto con revestimiento de felpa de microfibra interna premium específicas para la serie iPhone 16 Pro.",
    badge: "Silicon Pro",
    available: true,
    featured: true
  },
  {
    id: "fundas-silicon-protectoras-surtidas",
    name: "Fundas Silicon Case Protectoras Surtidas",
    category: "fundas",
    price: 7900,
    originalPrice: 10000,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673489/j8quir9coyns8datkvx7.jpg",
    description: "Gran variedad y surtido de fundas Silicon Case de colores vibrantes para múltiples marcas de celulares (Motorola, Samsung, Xiaomi, iPhone).",
    badge: "Surtido Completo",
    available: true,
    featured: false
  },
  {
    id: "vidrio-templado-anti-espia-premium",
    name: "Vidrio Templado Anti-Espía Premium",
    category: "vidrios",
    price: 5900,
    originalPrice: 7500,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673491/lohrt4j5l0knmkq7dmpd.jpg",
    description: "Vidrio templado protector con filtro inteligente de privacidad anti-espía. Evita que extraños miren tu pantalla desde los costados manteniendo nitidez HD de frente.",
    badge: "Privacidad Max",
    available: true,
    featured: true
  },
  {
    id: "servicio-tecnico-consulta-presupuesto",
    name: "Servicio Técnico Especializado - Consulta/Presupuesto",
    category: "otros",
    price: 0,
    originalPrice: null,
    image: "https://res.cloudinary.com/dgb5o9y0v/image/upload/v1779673492/gm5nvhksdcalfqqfhygz.jpg",
    description: "Servicio técnico oficial de celulares con más de 10 años en el rubro en Merlo Centro. Cotización de reparaciones, cambios de módulo, puerto de pin de carga y baterías.",
    badge: "Soporte Técnico",
    available: true,
    featured: true
  }
];

const initialConfig = {
  storeName: "Univercelu",
  tagline: "Más de 10 años en el rubro.",
  whatsapp: "5491136719257",
  instagram: "univercelu_merlo",
  deliveryZone: "Maipú 510, Merlo Centro (entre Libertador y Saranfi)",
  minOrder: 0,
  welcomeMessage: "¡Hola! Quisiera hacer un pedido de accesorios 📱"
};

window.initialProducts = initialProducts;
window.initialConfig   = initialConfig;
